[workspace]
resolver = "2"
members = ["packages/sapling-oxc-transformer"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
napi = { version = "2.14.1", default-features = false, features = ["napi4"] }
napi-derive = "2.14.1"
napi-build = "2.1.0"
oxc_allocator = "0.73.2"
oxc_ast = "0.73.2"
oxc_span = "0.73.2"
oxc_syntax = "0.73.2"
oxc_codegen = "0.73.2"
oxc_parser = "0.73.2"
oxc_transformer = "0.73.2"
oxc_semantic = "0.73.2"
insta = "1.34.0"
