[workspace]
resolver = "2"
members = [
    "packages/sapling_macros",
    "packages/sapling_shared",
    "packages/sapling_transformer",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
insta = "1.34.0"
