[package]
name = "sapling-oxc-transformer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
html5ever = "0.26"
markup5ever = "0.11"
markup5ever_rcdom = "0.2"
lazy_static = "1.4.0"
regex = "1.9"
napi = { workspace = true }
napi-derive = { workspace = true }
oxc_allocator = { workspace = true }
oxc_ast = { workspace = true }
oxc_span = { workspace = true }
oxc_syntax = { workspace = true }
oxc_codegen = { workspace = true }
oxc_parser = { workspace = true }
oxc_transformer = { workspace = true }
oxc_semantic = { workspace = true }
pico-args = "0.5.0"
oxc_ast_visit = "0.73.2"
oxc_traverse = "0.73.2"
indextree = "4.7.4"

[build-dependencies]
napi-build = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
