[package]
name = "sapling_ssr"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
sapling_core = { path = "../sapling_core" }
sapling_macros = { path = "../sapling_macros" }
sapling_shared = { path = "../sapling_shared" }

oxc_allocator = { workspace = true }
oxc_ast = { workspace = true }
oxc_span = { workspace = true }
oxc_syntax = { workspace = true }
oxc_codegen = { workspace = true }
oxc_parser = { workspace = true }
oxc_transformer = { workspace = true }
oxc_semantic = { workspace = true }
oxc_traverse = { workspace = true }

proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

lazy-regex = { workspace = true }
itertools = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
