[package]
name = "sapling_shared"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
sapling_macros = { path = "../sapling_macros" }

proc-macro2 = { workspace = true }
syn = { workspace = true }
prettyplease = { workspace = true }
cow-utils = { workspace = true }
lazy-regex = { workspace = true }
oxc_allocator.workspace = true
oxc_ast = { workspace = true }
oxc_span = { workspace = true }
oxc_syntax = { workspace = true }
oxc_codegen = { workspace = true }
oxc_parser = { workspace = true }
oxc_transformer = { workspace = true }
oxc_semantic = { workspace = true }
oxc_traverse = { workspace = true }

lazy_static = { workspace = true }
regex = { workspace = true }
phf = { workspace = true, features = ["macros"] }
phf_codegen = { workspace = true }
convert_case = { workspace = true }
indextree.workspace = true
html5ever.workspace = true
markup5ever.workspace = true
markup5ever_rcdom.workspace = true
oxc_ast_visit.workspace = true

[dev-dependencies]
insta = { workspace = true }
